In [1]:
import pandas as pd 
import seaborn as sns
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.feature_extraction.text import CountVectorizer,TfidfVectorizer
from sklearn.naive_bayes import MultinomialNB
from sklearn.metrics import accuracy_score
import string
import matplotlib.pyplot as plt

In [2]:
data = pd.read_csv("spam.tsv",sep='\t',names=['Class','Message'])#tsv---tab seperated value
data.head(8) 

Class                                            Message
0   ham  I've been searching for the right words to tha...
1  spam  Free entry in 2 a wkly comp to win FA Cup fina...
2   ham  Nah I don't think he goes to usf, he lives aro...
3   ham  Even my brother is not like to speak with me. ...
4   ham               I HAVE A DATE ON SUNDAY WITH WILL!!!
5   ham  As per your request 'Melle Melle (Oru Minnamin...
6  spam  WINNER!! As a valued network customer you have...
7  spam  Had your mobile 11 months or more? U R entitle...

In [3]:
data.loc[:0]

Class                                            Message
0   ham  I've been searching for the right words to tha...

In [4]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5567 entries, 0 to 5566
Data columns (total 2 columns):
 #   Column   Non-Null Count  Dtype 
---  ------   --------------  ----- 
 0   Class    5567 non-null   object
 1   Message  5567 non-null   object
dtypes: object(2)
memory usage: 87.1+ KB


In [5]:
data['Length']=data['Message'].apply(len)

In [6]:
data['Length']

0       196
1       155
2        61
3        77
4        36
       ... 
5562    160
5563     36
5564     57
5565    125
5566     26
Name: Length, Length: 5567, dtype: int64

In [7]:
data

Class                                            Message  Length
0      ham  I've been searching for the right words to tha...     196
1     spam  Free entry in 2 a wkly comp to win FA Cup fina...     155
2      ham  Nah I don't think he goes to usf, he lives aro...      61
3      ham  Even my brother is not like to speak with me. ...      77
4      ham               I HAVE A DATE ON SUNDAY WITH WILL!!!      36
...    ...                                                ...     ...
5562  spam  This is the 2nd time we have tried 2 contact u...     160
5563   ham               Will ü b going to esplanade fr home?      36
5564   ham  Pity, * was in mood for that. So...any other s...      57
5565   ham  The guy did some bitching but I acted like i'd...     125
5566   ham                         Rofl. Its true to its name      26

[5567 rows x 3 columns]

In [8]:
data.groupby('Class').count()

Message  Length
Class                 
ham       4821    4821
spam       746     746

# Data Visualization

In [9]:
data['Length'].describe()

count    5567.000000
mean       80.450153
std        59.891023
min         2.000000
25%        36.000000
50%        62.000000
75%       122.000000
max       910.000000
Name: Length, dtype: float64

In [10]:
data['Length']==910

0       False
1       False
2       False
3       False
4       False
        ...  
5562    False
5563    False
5564    False
5565    False
5566    False
Name: Length, Length: 5567, dtype: bool

In [11]:
#Maximum character
data[data['Length']==910]['Message']

1080    For me the love should start with attraction.i...
Name: Message, dtype: object

In [13]:
data[data['Length']==910]['Message'].iloc[0]

"For me the love should start with attraction.i should feel that I need her every time around me.she should be the first thing which comes in my thoughts.I would start the day and end it with her.she should be there every time I dream.love will be then when my every breath has her name.my life should happen around her.my life will be named to her.I would cry for her.will give all my happiness and take all her sorrows.I will be ready to fight with anyone for her.I will be in love when I will be doing the craziest things for her.love will be when I don't have to proove anyone that my girl is the most beautiful lady on the whole planet.I will always be singing praises for her.love will be when I start up making chicken curry and end up makiing sambar.life will be the most beautiful then.will get every morning and thank god for the day because she is with me.I would like to say a lot..will tell later.."

In [14]:
#Minimum character
data[data['Length']==2]['Message']

1920    Ok
3046    Ok
4493    Ok
5352    Ok
Name: Message, dtype: object

In [15]:
data[data['Length']==2]['Message'].iloc[0]

'Ok'

In [16]:
dObject=data['Class'].values
dObject

array(['ham', 'spam', 'ham', ..., 'ham', 'ham', 'ham'], dtype=object)

In [22]:
data.loc[data['Class']=='ham','Class'] =1


In [23]:
data.loc[data['Class']=='spam','Class'] =0


In [24]:
dObject2=data['Class'].values
dObject

array([1, 0, 1, ..., 1, 1, 1], dtype=object)

In [25]:
data

Class                                            Message  Length
0        1  I've been searching for the right words to tha...     196
1        0  Free entry in 2 a wkly comp to win FA Cup fina...     155
2        1  Nah I don't think he goes to usf, he lives aro...      61
3        1  Even my brother is not like to speak with me. ...      77
4        1               I HAVE A DATE ON SUNDAY WITH WILL!!!      36
...    ...                                                ...     ...
5562     0  This is the 2nd time we have tried 2 contact u...     160
5563     1               Will ü b going to esplanade fr home?      36
5564     1  Pity, * was in mood for that. So...any other s...      57
5565     1  The guy did some bitching but I acted like i'd...     125
5566     1                         Rofl. Its true to its name      26

[5567 rows x 3 columns]

# removing punctuations

In [27]:
import string 
string.punctuation

'!"#$%&\'()*+,-./:;<=>?@[\\]^_`{|}~'

In [33]:
def remove_punct(text):
    text="".join([char for char in text if char not in string.punctuation])
    return text
data['Text_clean']=data['Message'].apply(lambda x:remove_punct(x))
data.head()
# def remove_punct(text):
#     text = "".join([char for char in text if char not in string.punctuation])#the punctuations which are present in the string only that punc will get removed
#     return text

# data['text_clean'] = data['Message'].apply(lambda x: remove_punct(x))

# data.head()

Class                                            Message  Length  \
0     1  I've been searching for the right words to tha...     196   
1     0  Free entry in 2 a wkly comp to win FA Cup fina...     155   
2     1  Nah I don't think he goes to usf, he lives aro...      61   
3     1  Even my brother is not like to speak with me. ...      77   
4     1               I HAVE A DATE ON SUNDAY WITH WILL!!!      36   

                                          Text_clean  
0  Ive been searching for the right words to than...  
1  Free entry in 2 a wkly comp to win FA Cup fina...  
2  Nah I dont think he goes to usf he lives aroun...  
3  Even my brother is not like to speak with me T...  
4                  I HAVE A DATE ON SUNDAY WITH WILL

In [34]:
CV=CountVectorizer(stop_words='english')

In [37]:
xSet=data['Text_clean'].values
ySet=data['Class'].values

In [39]:
xSet

array(['Ive been searching for the right words to thank you for this breather I promise i wont take your help for granted and will fulfil my promise You have been wonderful and a blessing at all times',
       'Free entry in 2 a wkly comp to win FA Cup final tkts 21st May 2005 Text FA to 87121 to receive entry questionstd txt rateTCs apply 08452810075over18s',
       'Nah I dont think he goes to usf he lives around here though', ...,
       'Pity  was in mood for that Soany other suggestions',
       'The guy did some bitching but I acted like id be interested in buying something else next week and he gave it to us for free',
       'Rofl Its true to its name'], dtype=object)

In [40]:
ySet

array([1, 0, 1, ..., 1, 1, 1], dtype=object)

In [44]:
ySet=ySet.astype('int')

# Splitting train and test

In [46]:
xSet_train,xSet_test,ySet_train,ySet_test=train_test_split(xSet,ySet,test_size=0.2,random_state=40)

In [47]:
xSet_train_CV = CV.fit_transform(xSet_train)

In [48]:
xSet_train_CV

<4453x8204 sparse matrix of type '<class 'numpy.int64'>'
	with 34844 stored elements in Compressed Sparse Row format>

# training model

In [49]:
NB = MultinomialNB()#training the model

In [51]:
NB.fit(xSet_train_CV,ySet_train)

MultinomialNB()

In [52]:
xSet_test_CV = CV.transform(xSet_test)

In [53]:
ySet_predict = NB.predict(xSet_test_CV)
ySet_predict

array([1, 1, 0, ..., 1, 1, 0])

In [54]:
accuracyScore = accuracy_score(ySet_test,ySet_predict)*100

print("Prediction Accuracy :",accuracyScore)

Prediction Accuracy : 98.1149012567325


### SpamClassificationApplication

In [57]:
msg = input("Enter Message: ") # to get the input message
msgInput = CV.transform([msg]) # 
predict = NB.predict(msgInput)
if(predict[0]==0):
    print("------------------------MESSAGE-SENT-[CHECK-SPAM-FOLDER]---------------------------")
else:
    print("---------------------------MESSAGE-SENT-[CHECK-INBOX]------------------------------")

Enter Message:  I've been searching for the right words to tha...


---------------------------MESSAGE-SENT-[CHECK-INBOX]------------------------------


# Bag of words

In [58]:
documents = ["Dog bites man.", "Man bites dog.", "Dog eats meat.", "Man eats food."]

# Changing the text to lower case and remove the full stop from text
processed_docs = [doc.lower().replace(".","") for doc in documents]
processed_docs[3]

'man eats food'

In [59]:
print("Our corpus: ", processed_docs)

Our corpus:  ['dog bites man', 'man bites dog', 'dog eats meat', 'man eats food']


In [60]:
count_vect = CountVectorizer()


In [61]:
bow_rep = count_vect.fit_transform(processed_docs)


In [62]:
print("Our vocabulary: ", count_vect.vocabulary_)


Our vocabulary:  {'dog': 1, 'bites': 0, 'man': 4, 'eats': 2, 'meat': 5, 'food': 3}


In [63]:
print("BoW representation for 'dog bites man': ", bow_rep[0].toarray())

BoW representation for 'dog bites man':  [[1 1 0 0 1 0]]


In [64]:
print("BoW representation for 'man bites dog: ",bow_rep[1].toarray())


BoW representation for 'man bites dog:  [[1 1 0 0 1 0]]


In [65]:
temp = count_vect.transform(["dog and dog are friends"])
print("Bow representation for 'dog and dog are friends':", temp.toarray())

Bow representation for 'dog and dog are friends': [[0 2 0 0 0 0]]


## TF-IDF

In [69]:
X = data['Text_clean'].values
y = data['Class'].values
y

array([1, 0, 1, ..., 1, 1, 1], dtype=object)

In [70]:
y = y.astype('int')
y

array([1, 0, 1, ..., 1, 1, 1])

In [71]:
from sklearn.feature_extraction.text import TfidfVectorizer


tf=TfidfVectorizer() ## object creation
X=tf.fit_transform(X)

In [72]:
X.shape

(5567, 9537)

In [73]:
X=X.toarray()

In [74]:
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test=train_test_split(X,y,random_state=6)

In [75]:
from sklearn.naive_bayes import BernoulliNB

## model object creation
nb=BernoulliNB(alpha=0.01) 

## fitting the model
nb.fit(X_train,y_train)

## getting the prediction
y_hat=nb.predict(X_test) 

In [76]:
y_hat

array([1, 1, 1, ..., 1, 1, 1])

In [77]:
from sklearn.metrics import classification_report,confusion_matrix

In [78]:
print(classification_report(y_test,y_hat))

              precision    recall  f1-score   support

           0       0.96      0.96      0.96       186
           1       0.99      0.99      0.99      1206

    accuracy                           0.99      1392
   macro avg       0.98      0.98      0.98      1392
weighted avg       0.99      0.99      0.99      1392



In [79]:
pd.crosstab(y_test,y_hat)

col_0    0     1
row_0           
0      178     8
1        7  1199