# Numpy
#importing the libraries
import numpy as np
import pandas as pd

In [78]:
import numpy as np 
import pandas as pd
#Generating the random variables
exp=np.random.normal(500,700,100)

In [10]:
exp

array([  987.11011443,  -262.75720883,  -159.88036586,   471.05090967,
        1316.41591886,   872.94630244,   703.22094473,  1067.5979963 ,
         193.32148506,   547.43960308,   602.40062127,   675.34119547,
        2264.54091447,    98.80164004,  1917.38411466,  -458.84585642,
         964.27690621,   308.82131425,    90.28285675,  -235.29628227,
           4.48224479,   577.9334316 ,   292.66148251,  -180.23070603,
          18.8349811 ,  -300.46430708,  1357.7040686 ,   261.62592951,
         690.025218  ,   -89.7854421 ,  1054.65891068,   453.43116672,
          75.63745816,   689.90937858,  -161.53440316,    20.22012442,
        -122.05543076,   -16.15965825,   826.10690314,   148.92317038,
         531.82902883,   547.6045899 ,   -29.66425424,   717.04429158,
         417.64518893,   -48.66967516,  -184.78151133,  1277.01074393,
         571.13111412,  -165.28777963,   694.68033072,  1740.49855406,
        -291.55071307,   324.06740957,  2203.93671361,     8.42994313,
      

In [11]:
#calculating the mean
np.mean(exp)

519.3758695489466

In [12]:
#calculating the median
np.median(exp)

489.49832816849505

In [13]:
import statistics as st

In [15]:
st.mode(exp)

987.110114426634

In [16]:
data=[1,2,3,4,5,6,7,8]

In [17]:
st.mode(data)

1

In [18]:
exp=np.append(exp,[10000000])

In [19]:
exp

array([ 9.87110114e+02, -2.62757209e+02, -1.59880366e+02,  4.71050910e+02,
        1.31641592e+03,  8.72946302e+02,  7.03220945e+02,  1.06759800e+03,
        1.93321485e+02,  5.47439603e+02,  6.02400621e+02,  6.75341195e+02,
        2.26454091e+03,  9.88016400e+01,  1.91738411e+03, -4.58845856e+02,
        9.64276906e+02,  3.08821314e+02,  9.02828568e+01, -2.35296282e+02,
        4.48224479e+00,  5.77933432e+02,  2.92661483e+02, -1.80230706e+02,
        1.88349811e+01, -3.00464307e+02,  1.35770407e+03,  2.61625930e+02,
        6.90025218e+02, -8.97854421e+01,  1.05465891e+03,  4.53431167e+02,
        7.56374582e+01,  6.89909379e+02, -1.61534403e+02,  2.02201244e+01,
       -1.22055431e+02, -1.61596582e+01,  8.26106903e+02,  1.48923170e+02,
        5.31829029e+02,  5.47604590e+02, -2.96642542e+01,  7.17044292e+02,
        4.17645189e+02, -4.86696752e+01, -1.84781511e+02,  1.27701074e+03,
        5.71131114e+02, -1.65287780e+02,  6.94680331e+02,  1.74049855e+03,
       -2.91550713e+02,  

In [20]:
np.mean(exp)

99524.13452430589

In [21]:
np.median(exp)

507.94574666288946

In [24]:
st.variance(exp)

989996694506.0139

In [25]:
st.stdev(exp)

994985.7760320064

In [52]:
from scipy import stats
data=[23,45,67,89,87,46,22,32,54,65,76,12,98,9]

In [53]:
IQR=stats.iqr(data,interpolation='midpoint')

In [54]:
IQR

44.0

In [55]:
len(data)

14

In [56]:
data.sort()

In [57]:
data

[9, 12, 22, 23, 32, 45, 46, 54, 65, 67, 76, 87, 89, 98]

In [58]:
q1_loc=(len(data)+1)*25/100
q1_loc

3.75

In [59]:
q3_loc=(len(data)+1)*75/100
q3_loc

11.25

In [65]:
q1=data[3]+0.75*(data[3]-data[2]) #q1=data[5]+0.25*(data[5]-data[4])
q1

23.75

In [64]:
q3=data[11]+0.25*(data[11]-data[10])
q3

89.75

In [66]:
data[11]

87

In [67]:
data[3]

23

In [68]:
q3-q1

66.0

In [75]:
#Boxplot
ub=q3+1.5*(IQR)
ub

155.75

In [76]:
lb=q3-1.5*(IQR)
lb

23.75

In [77]:
print('Outliers')
for i in data:
    if i<lb:
        print(i)
    if i>ub:
        print(i)

Outliers
9
12
22
23


# Pandas

In [79]:
import pandas as pd

In [80]:
#Creating the empty series
a=pd.Series(12)

In [81]:
a

0    12
dtype: int64

In [82]:
#Using tuple
t=(1,2,3,4,5,6)
pd.Series(t)

0    1
1    2
2    3
3    4
4    5
5    6
dtype: int64

In [83]:
#Using List
l=[1,12,13,14,15,16,17]
pd.Series(l)

0     1
1    12
2    13
3    14
4    15
5    16
6    17
dtype: int64

In [86]:
#Creating series with array
import numpy as np
a=np.array([10,20,30,40,50])
d1=pd.Series(a)
d1

0    10
1    20
2    30
3    40
4    50
dtype: int32

In [92]:
arr1=np.array([[1,2],[4,5],[5,6],[10,20]])
arr1

array([[ 1,  2],
       [ 4,  5],
       [ 5,  6],
       [10, 20]])

In [93]:
arr1.shape

(4, 2)

In [94]:
s=pd.Series(arr1)

ValueError: Data must be 1-dimensional, got ndarray of shape (4, 2) instead

In [95]:
#this error occured becoz Series is 1D only and the given array here is 2D

In [96]:
#USing Dictionary
a = {'a':1,'b':'sejal','c':'jayesh'}

In [97]:
d2=pd.Series(a)

In [98]:
d2

a         1
b     sejal
c    jayesh
dtype: object

In [99]:
a['a']

1

In [100]:
a['b']

'sejal'

In [101]:
a['c']

'jayesh'

In [102]:
#Slicing operation
d=pd.Series([1,2,23,44,5,6,77,8,9,90,100,32,43,54,65,55,64,63,73])

In [103]:
d[6]

77

In [104]:
d[[6,7,8,9,10]]

6      77
7       8
8       9
9      90
10    100
dtype: int64

In [107]:
d[3:10]=[13,14,15,16,17,18,200]
d

0       1
1       2
2      23
3      13
4      14
5      15
6      16
7      17
8      18
9     200
10    100
11     32
12     43
13     54
14     65
15     55
16     64
17     63
18     73
dtype: object

In [110]:
arr9=np.array[10,20,30,40]
d4=pd.Series(arr9,index=['one','b','c','d'])
d4

TypeError: 'builtin_function_or_method' object is not subscriptable