In [1]:
import numpy as np

In [6]:
arr1=np.array([])

In [7]:
arr1

array([], dtype=float64)

In [8]:
my_list=[1,2,3,4]
print(my_list)
print(type(my_list))

[1, 2, 3, 4]
<class 'list'>


In [15]:
b=np.array(my_list)

In [16]:
b

array([1, 2, 3, 4])

In [17]:
type(b)

numpy.ndarray

In [19]:
b.ndim

1

In [20]:
b.shape

(4,)

In [21]:
b.size

4

In [22]:
m1=[[1,2,3,4],[5,6,7,8],[9,10,11,12]]

In [23]:
m1

[[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]]

In [24]:
q = np.array(m1)

In [25]:
q

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [27]:
q.ndim

2

In [28]:
q.shape

(3, 4)

In [29]:
q.size

12

In [34]:
print("Computer does not understand our language:", b.size)

Computer does not understand our language: 4


In [35]:
print("jayesh is a good coder:",b.shape)

jayesh is a good coder: (4,)


In [36]:
print("jayesh is a good coder:",b.ndim)

jayesh is a good coder: 1


In [37]:
print("jayesh is a good coder:",b.dtype)

jayesh is a good coder: int32


In [38]:
arr2 = np.array([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]])

In [39]:
arr2

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [41]:
r = np.array(arr2)

In [42]:
r

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [43]:
r.shape

(2, 2, 3)

In [47]:
r.reshape(1,3,4)

array([[[ 1,  2,  3,  4],
        [ 5,  6,  7,  8],
        [ 9, 10, 11, 12]]])

In [51]:
np.arange(15)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [53]:
np.arange(100,1,-4)

array([100,  96,  92,  88,  84,  80,  76,  72,  68,  64,  60,  56,  52,
        48,  44,  40,  36,  32,  28,  24,  20,  16,  12,   8,   4])

In [54]:
np.zeros(4)

array([0., 0., 0., 0.])

In [58]:
np.zeros((3,3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [59]:
np.ones((1,3))

array([[1., 1., 1.]])

In [61]:
np.ones((4,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [64]:
np.linspace(1,100,15)

array([  1.        ,   8.07142857,  15.14285714,  22.21428571,
        29.28571429,  36.35714286,  43.42857143,  50.5       ,
        57.57142857,  64.64285714,  71.71428571,  78.78571429,
        85.85714286,  92.92857143, 100.        ])

In [65]:
np.linspace(1,16, retstep=True)

(array([ 1.        ,  1.30612245,  1.6122449 ,  1.91836735,  2.2244898 ,
         2.53061224,  2.83673469,  3.14285714,  3.44897959,  3.75510204,
         4.06122449,  4.36734694,  4.67346939,  4.97959184,  5.28571429,
         5.59183673,  5.89795918,  6.20408163,  6.51020408,  6.81632653,
         7.12244898,  7.42857143,  7.73469388,  8.04081633,  8.34693878,
         8.65306122,  8.95918367,  9.26530612,  9.57142857,  9.87755102,
        10.18367347, 10.48979592, 10.79591837, 11.10204082, 11.40816327,
        11.71428571, 12.02040816, 12.32653061, 12.63265306, 12.93877551,
        13.24489796, 13.55102041, 13.85714286, 14.16326531, 14.46938776,
        14.7755102 , 15.08163265, 15.3877551 , 15.69387755, 16.        ]),
 0.30612244897959184)

In [66]:
sej = np.ones((3,4))

In [67]:
sej

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [68]:
sej*3

array([[3., 3., 3., 3.],
       [3., 3., 3., 3.],
       [3., 3., 3., 3.]])

In [73]:
w = np.array(sej*6-0.2, dtype='int')

In [74]:
w

array([[5, 5, 5, 5],
       [5, 5, 5, 5],
       [5, 5, 5, 5]])

In [75]:
w = np.array(sej*6-0.2)

In [76]:
w

array([[5.8, 5.8, 5.8, 5.8],
       [5.8, 5.8, 5.8, 5.8],
       [5.8, 5.8, 5.8, 5.8]])

In [78]:
arr2=np.arange(20)
2/arr2

C:\Users\Dell\AppData\Local\Temp\ipykernel_14232\209768123.py:2: RuntimeWarning: divide by zero encountered in divide
  2/arr2


array([       inf, 2.        , 1.        , 0.66666667, 0.5       ,
       0.4       , 0.33333333, 0.28571429, 0.25      , 0.22222222,
       0.2       , 0.18181818, 0.16666667, 0.15384615, 0.14285714,
       0.13333333, 0.125     , 0.11764706, 0.11111111, 0.10526316])

In [79]:
arr2 + arr2


array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32,
       34, 36, 38])

In [80]:
arr3 = arr2

In [81]:
arr3


array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [82]:
arr3[:10]=10

In [83]:
arr3

array([10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [84]:
arr3[10:]=50

In [85]:
arr3

array([10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 50, 50, 50, 50, 50, 50, 50,
       50, 50, 50])

In [86]:
arr3[10:5]=20

In [87]:
arr3


array([10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 50, 50, 50, 50, 50, 50, 50,
       50, 50, 50])